name: Kernel Config - A16 6.1

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_dispatch: # This allows you to click "Run Workflow" manually
  workflow_call:
    inputs: {}

jobs:
  build-kernels-a16-6-1:
    name: "A16-6.1.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "145"
            os_patch_level: "2025-08"
          - sub_level: "145"
            os_patch_level: "2025-09"
          - sub_level: "148"
            os_patch_level: "2025-10"
          - sub_level: "152"
            os_patch_level: "2025-11"
          - sub_level: "155"
            os_patch_level: "2025-12"
          - sub_level: "160"
            os_patch_level: "2026-01"
          - sub_level: "164"
            os_patch_level: "2026-02"
          - sub_level: "168"
            os_patch_level: "2026-03"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android16"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
